### ISSUE TITLE
Error adding entities

### ISSUE THREAD

**Issue by ffidan61** [engrbm87/HA-islamic-prayer-times#4]
First of all thank you for this integration.
Somehow I got this error today. I tried reinstalling didn't helped

Version | core-2022.3.1
-- | --
Installationstyp | Home Assistant Container
Entwicklung | false
Supervisor | false
Docker | true
Benutzer | root
Virtuelle Umgebung | false
Python-Version | 3.9.9
Betriebssystemfamilie | Linux
Betriebssystem-Version | 5.4.0-100-generic
CPU-Architektur | x86_64
Zeitzone | Europe/Berlin

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:392
Integration: Sensor (documentation, issues)
First occurred: 10:24:12 (2 occurrences)
Last logged: 10:24:12

Error adding entities for domain sensor with platform islamic_prayer_times
Error while setting up islamic_prayer_times platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 381, in state
    if value.tzinfo is None:
AttributeError: 'str' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 783, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 392, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.fajer_prayer has a timestamp device class but does not provide a datetime state but <class 'str'>

**Comment by Alshukaily** [comment]
I don't know if I have the same problem but suddenly all times showing UNAVAILABLE, usually restarting home assistant fix this issue, but now it doesn't help even reinstalling doesn't fix it.

**Comment by amamdani15** [comment]
As far as the UNAVAILABLE issue is concerned, i was in the same boat as you. restarting would fix it for a while and then it stopped working altogether. 

It seemed that on startup, it was trying to do two updates to the time back to back and that was overloading the API that it levarges. 

Take a look at this commit, I forked it into my own repo and use it from there now. https://github.com/amamdani15/HA-custom-components/commit/f070d9dc48d1fece172ff304ab2a2c7e018f8884

**Comment by ffidan61** [comment]
Thanks for the info, I tried your repo sadly didn't work for me.

**Comment by amamdani15** [comment]
I have other changes as well, you may have to set the settings to make it work.

I would recommend forking to your own repo and just commenting out the same lines I did in that commit
